More robust startup checks

diff --git a/bin/runarbiter b/bin/runarbiter
--- a/bin/runarbiter
+++ b/bin/runarbiter
@@ -15,6 +15,7 @@ if [[ -z "$TSERVER_ADDRESS" ]]; then
 	exit 1
 fi
 
+did=$(
 docker run \
 	--name tm_arbiter \
 	-d \
@@ -24,3 +25,18 @@ docker run \
 	-e "ARBITER_ADDRESS=$ARBITER_ADDRESS" \
 	-e "ARBITER_SECRET=$ARBITER_SECRET" \
 	mapio/tm-arbiter
+)
+
+echo -en "Waiting for arbiter startup"
+attempts=10
+while [[ $attempts > 0 ]] && ! docker logs tm_arbiter | grep 'arbiter started' >/dev/null; do
+	echo -n .
+	sleep 1
+	attempts=$(( $attempts - 1 ))
+done
+if [[ $attempts > 0 ]]; then
+	echo ". started ($did)!"
+else
+	echo " FAILED TO START!"
+	exit 1
+fi
diff --git a/bin/runtserver b/bin/runtserver
--- a/bin/runtserver
+++ b/bin/runtserver
@@ -12,6 +12,7 @@ fi
 
 export TM_CONFIGS=$(realpath $TM_CONFIGS)
 
+did=$(
 docker run \
 	--name tm_tserver \
 	-d \
@@ -19,3 +20,18 @@ docker run \
 	-v $(pwd)/uploads:/app/uploads \
 	-p 8000:8000 \
 	mapio/tm-tserver
+)
+
+echo -en "Waiting for tserver startup"
+attempts=10
+while [[ $attempts > 0 ]] && ! docker logs tm_tserver | grep 'tserver started' >/dev/null; do
+	echo -n .
+	sleep 1
+	attempts=$(( $attempts - 1 ))
+done
+if [[ $attempts > 0 ]]; then
+	echo ". started ($did)!"
+else
+	echo " FAILED TO START!"
+	exit 1
+fi
