Added few support scripts

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,10 +1,18 @@
 #!/bin/bash
 
+echoerr() {
+	echo "$@" 1>&2
+}
+
+exiterr() {
+	exit 1
+}
+
 ip=$(boot2docker ip)
 user_key=$1
 
 if [ -z $user_key ]; then
-	echo "Must specify user:key"
+	echoerr "Must specify user:key"
 	exit 1
 fi
 
@@ -15,12 +23,12 @@ did=''
 if [[ -r "./data/${user}.did" ]]; then
 
 	did=$(cat "./data/${user}.did")
-	echo -n "Found previous run id '$did'..."
+	echoerr -n "Found previous run id '$did'..."
 	running=$(docker inspect -f '{{ .State.Running }}' $did 2>/dev/null)
 	if [[ $running == "true" ]]; then
-		echo " instance alive!"
+		echoerr " instance alive!"
 	else
-		echo " instance not running! Cleaning up id..."
+		echoerr " instance not running! Cleaning up id..."
 		did=''
 		rm -f "./data/${user}.did"
 	fi
@@ -29,19 +37,25 @@ fi
 
 if [[ -z "$did" ]]; then
 
-	echo -n "Starting for user '$user' and key '$key'..."
-
 	if [[ ! -d "./data/$user" ]]; then
 		mkdir -p "./data/$user"
 	fi
-	did=$(docker run -d -P -v $(pwd)/data:/data  mapio/codebox4im-docker run --users $user_key "$user")
+
+	did=$(docker run --name "cb_${user}" -d -P -v $(pwd)/data:/data mapio/codebox4im-docker run --users $user_key "$user" && sleep 1)
+	echoerr "Started for user '$user', key '$key', did '$did'"
 	echo $did > "./data/${user}.did"
-	echo " $did."
 fi
 
 port=$(docker port $did)
 port=${port##*:}
-echo "Server running on port '$port'"
 
-echo curl http://$ip:$port/
+if curl -s http://$ip:$port/ | grep -q '<title>Codebox</title>'; then
+	echoerr "Server running on port '$port', homepage ok!"
+	echo "{ \"user\": \"$user\", \"key\": \"$key\", \"did\": \"$did\", \"port\": \"$port\", \"status\": \"ok\" }"
+else
+	echoerr "Somehting wrong happened, curl cant't retrieve the homepage!"
+	echo "{ \"user\": \"$user\", \"key\": \"$key\", \"status\": \"error\" }"
+	exit 1
+fi
+
 
